### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by wikkyk** [ionos-cloud/cluster-api-provider-proxmox#119]
## Release

Release v0.4.0

## Checklist

- [ ] Update metadata & clusterctl-settings
- [ ] Update docs, (compatibility table, usage etc) .
- [ ] Create tag.
- [ ] Update the created draft release to include (BREAKING Changes, Important Notes).
- [ ] Publish the release.

**Comment by 65278** [comment]
Selected for this release. Most of these are production issues. I included all the documentation because those are small and don't require testing:

- [ ] Docoumentation for this image builder environment vars: https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/52
- [ ] controlPlaneEndpoint hostname support:https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/153
- [ ] IPv6 kube-vip documentation: https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/144
- [ ] Fix a templating bug for cloudinit in VRF. No issue yet
- [ ] Merge ClusterClass PR (99.9% done).
- [ ] MTU for all interfaces (not just the default interface). Subset of refactoring cloudinit configuration.
- [ ] Document VM deletion/reconcilation deadlock (Finalizer needs to be removed).
- [ ] Document Calico IPVS network selection being wrong with multiple interfaces.

**Comment by CiraciNicolo** [comment]
Hello! Sorry to bother, any update on this? 

Thanks 😊

**Comment by wikkyk** [comment]
@CiraciNicolo we are about to make a release, most likely today or tomorrow.

**Comment by wikkyk** [comment]
Done!
